name: CI
on: [push]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x, 1.15.x]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -coverprofile coverage.xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-wiki-crawler
          fail_ci_if_error: true